[meta]
title = "Flask Text Intelligence Starter"
description = "Get started using Deepgram's Text Intelligence with this Flask demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
repository = "https://github.com/deepgram-starters/flask-text-intelligence"
useCase = "Text Intelligence"
language = "Python"
framework = "Flask"

[build]
command = "make init"

[config]
DEEPGRAM_API_KEY = "YOUR_DEEPGRAM_API_KEY"

[dev]
command = "make dev"

[start]
command = "make start"
